"""add shelves

Revision ID: 4634f0ac9905
Revises: c5f87eb6ebdd
Create Date: 2025-12-31 21:28:42.764525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4634f0ac9905'
down_revision: Union[str, None] = 'c5f87eb6ebdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_shelves_user_name')
    )
    op.create_index(op.f('ix_shelves_user_id'), 'shelves', ['user_id'], unique=False)
    op.create_table('shelf_books',
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shelf_id', 'book_id'),
    sa.UniqueConstraint('shelf_id', 'book_id', name='uq_shelf_books_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_books')
    op.drop_index(op.f('ix_shelves_user_id'), table_name='shelves')
    op.drop_table('shelves')
    # ### end Alembic commands ###
